name: Centos7 CI (push and/or release)

on:
  release:
    types: [created]
  push:
    branches:
      - develop
      - only-centos-ci
      - dependabot/*
  schedule:
    - cron: '21 2 * * *'
  workflow_call:
    inputs:
      run-tests:
        required: true
        type: string
      target_branch:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ github.token }}
  IS_RELEASE: ${{ github.event_name == 'workflow_dispatch' }}
  IS_PUSH: ${{ github.event_name == 'push' }}
  REF: ${{ inputs.target_branch =='' && github.ref_name || inputs.target_branch}}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:

      - name: Build the image and Antares
        run: |
            docker build \
            --target build \
            -t Antares:centos7 \
            --build-arg="ORTOOLS_TAG=$(cat ortools_tag)" \
            --build-arg="BRANCH=${{ env.REF }}" \
            --build-arg="NPROC=$(nproc)" \
            -f docker/Dockerfile .


      - name: create without starting a container && retrieve the .tgz
        run: |
          container_id=$(docker create Antares:centos7)
          mkdir archive
          docker cp $container_id:/workspace/Antares_Simulator/_build/antares-9.2.0-rc5-CentOS-7.9.2009.tar.gz archive/ 
          docker rm $container_id

      - name: Install gh if needed
        if: ${{ env.IS_RELEASE == 'true' }}
        run: |
            wget https://github.com/cli/cli/releases/download/v2.52.0/gh_2.52.0_linux_amd64.rpm
            rpm -i gh_2.52.0_linux_amd64.rpm
            gh --version

      - name: Publish assets
        if: ${{ env.IS_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tag: ${{ github.event.inputs.release_tag }}
        run: |
          gh release upload "$tag" archive/*.tar.gz _build/*.rpm

      - name: Cache vcpkg binary dir
        if: always()
        id: save-cache-vcpkg-binary
        uses: actions/cache/save@v3
        with:
          path: ${{ env.VCPKG_CACHE_DIR }}
          key: vcpkg-cache-centos7-${{ hashFiles('src/vcpkg.json', '.git/modules/vcpkg/HEAD') }}
